title: Hello. This is patsimm.
email: patrick.simmelbauer@gmail.com
description: >-
  patsimm - Human. Explorer. Developer.
baseurl: ""
url: "http://patsimm.com"
github_username:  patsimm

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

gems:
- octopress-autoprefixer


collections:
  subsites:
    output: true
    permalink: /:collection/:name:output_ext

exclude:
  - Dockerfile
  - nginx.conf
  - README.md
  - deploy_key.enc
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
