---
title: Hello. This is patsimm.
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  subsites:
    title: Subsites
    output: true
    permalink: "/:collection/:name:output_ext"
  uploads:
    title: Uploads
    output: true
email: patrick.simmelbauer@gmail.com
description: patsimm - Human. Explorer. Developer.
baseurl:
url: http://patsimm.com
github_username: patsimm
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-menus
exclude:
- Dockerfile
- nginx.conf
- README.md
- deploy_key.enc
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- gulpfile.js
- package.json
- package-lock.json
