backend:
  backend:
  name: github
  repo: patsimm/patsimm.com
  base_url: http://patsimm.com

media_folder: media_folder

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
